set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-ghostty:RGB"
set -ga terminal-features ",xterm-ghostty:usstyle"

set -g focus-events on

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind g display-popup -E -w 90% -h 90% -d "#{pane_current_path}" lazygit
bind r source-file ~/.config/tmux/tmux.conf

# sesh session picker (prefix + T)
bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d kill' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""
set -g detach-on-destroy off # killing a session switches to the next one instead of detaching

set -g mouse on

set -g status-position bottom

set-option -g allow-rename on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g history-limit 50000 # scrollback history

# vim keybinds
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session' # restore nvim sessions if you use :mksession
set -g @continuum-restore 'off' # manual reboot is prefix + C-r
set -g @continuum-save-interval '5' # manual save is prefix + C-s

set -g @rose_pine_variant 'main'
set -g @rose_pine_bar_bg_disable 'off'
set -g @rose_pine_host 'on'
set -g @rose_pine_directory 'on'

run '~/.config/tmux/plugins/tpm/tpm'
